config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get "edit_role/:id", to: "users#edit_role", as: "edit_role"
    end
  end
  resources :posts do
  	collection do
    	get "index_published", to: 'posts#index_published', as: 'published'
    	put "publish/:id" , to: 'posts#publish', as: 'publish'
      put "unpublish/:id" , to: 'posts#unpublish', as: 'unpublish'
  	end
    member do
      put "upvote", to: "posts#upvote"
      put "downvote", to: "posts#downvote"
    end
    # member do
    #   put 'like' => 'post#upvote'
    # end
  end

  get 'tags/:tag', to: 'posts#index', as: 'tag'
  get 'tags_published/:tag', to: 'posts#index_published', as: 'tags_published'

  root 'posts#index_published'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    if user.role == "admin"
        can :manage, :all 
    elsif user.role == "editor"
        can :update, Post
    elsif user.role == "user"
        can [:index_published, :show, :new, :create], Post
        cannot :edit, Post
    else
        can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :body, presence: true, length: { minimum: 20 }
	acts_as_taggable
	acts_as_votable
	ActsAsTaggableOn.remove_unused_tags = true

	# not used 
	# ment for search 
	def self.search(search)
	  if search
	    where('body LIKE ?', "%#{search}%")
	  else
	    scoped
	  end
	end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CanCan::ControllerAdditions	 
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
  	if resource.role == "admin"
  		posts_path
  	else
  		published_posts_path	
  	end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index_published, :show, :create, :upvote]
	respond_to :js, :json, :html
	load_and_authorize_resource
	
	def index
		if params[:tag]
			@posts = Post.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 5).order(created_at: :desc)
		else
			#paginates and orders by newest first
			@posts = Post.paginate(:page => params[:page], :per_page => 5).order(created_at: :desc)
		end
		@tags = ActsAsTaggableOn::Tag.most_used(6)

	end

	def top_last_n_hours(hoursN = 24)
		if params[:tag]
			@posts = Post.where('created_at > ?', hoursN.hours.ago).tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 5).order(created_at: :desc)
		else
			#paginates and orders by newest first
			@posts = Post.where('created_at > ?', hoursN.hours.ago).paginate(:page => params[:page], :per_page => 5).order(created_at: :desc)
		end
		@tags = ActsAsTaggableOn::Tag.most_used(6)
	end

	def index_published
		# this is the news feed

		# last 24 hours
		# most upvoted posts
		if params[:tag]
			@posts = Post.where(published: true).tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 5).order(cached_votes_score: :desc, created_at: :desc)
		elsif params[:search]
			@posts = Post.where(published: true).search(params[:search]).paginate(:page => params[:page], :per_page => 5).order(cached_votes_score: :desc, created_at: :desc)
		else
			@posts = Post.where(published: true).paginate(:page => params[:page], :per_page => 10).order(cached_votes_score: :desc, created_at: :desc)
		end
		@tags = ActsAsTaggableOn::Tag.most_used(5)
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)
		#@post = Post.new(post_params)
 
		if @post.save
		   redirect_to published_posts_path
		else
		   render 'new'
		end
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	#custom method


	# make the post public
	def publish
		@post = Post.find(params[:id])
		@post.published = true
		#@post.update(published: true)
		@post.save

		redirect_to posts_path
	end

	def unpublish
		@post = Post.find(params[:id])
		@post.published = false
		#@post.update(published: true)
		@post.save

		redirect_to posts_path
	end


	## TAGS
	def tag_cloud
	    @tags = Post.tag_counts_on(:tags)
	end

	def destroy_unused_tags
		@tags_to_delete = ActsAsTaggableOn::Tag.where('taggings_count' != 0)
		@tags_destroy_all
	end
	########

	## Vote system
	def upvote
		if !current_user.liked? @post
			@post.liked_by current_user
		elsif current_user.liked?@post
			@post.unliked_by current_user
		end
		respond_to do |format|
	    format.html { redirect_to :back }
	    format.js
	    end
	end
	def downvote
		if !current_user.disliked? @post
			@post.disliked_by current_user
		elsif current_user.disliked?@post
			@post.undisliked_by current_user
		end
		respond_to do |format|
	    format.html { redirect_to :back }
	    format.js
	    end
	end


private
	def post_params
		params.require(:post).permit(:body, :published, :tag_list)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!


	def index
		@users = User.paginate(:page => params[:page], :per_page => 5)
	end

	def show
	    @user = User.find(params[:id])
	    unless current_user.admin?
	      unless @user == current_user
	        redirect_to :back, :alert => "Access denied."
	      end
	    end
	 end

	def edit_role
		@user = User.find(params[:id])
	end

	
	def update
	    @user = User.find(params[:id])
	    if @user.update_attributes(secure_params)
	      redirect_to users_path, :notice => "User updated."
	    else
	      redirect_to users_path, :alert => "Unable to update user."
	    end
	end

	def destroy
	    user = User.find(params[:id])
	    user.destroy
	    redirect_to users_path, :notice => "User deleted."
	end


	private
	
	def secure_params
	   params.require(:user).permit(:role)
	end


	def admin_only
		unless current_user.role == "admin"
			redirect_to :back, :alert => "Access Denied"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper


	#currently not used 
	# def sortable(column, title = nil)
	#   title ||= column.titleize
	#   css_class = column == sort_column ? "current #{sort_direction}" : nil
	#   direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	#   link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	# end
end

app/helpers/posts_helper.rb
module PostsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bayan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
      <nav class="navbar navbar-full navbar-light bg-faded">
            <div class="navbar-header">
              <%= link_to "Melbourne Anon", published_posts_path, :class => 'navbar-brand' %>
            </div>
            <ul class="nav nav-pills ">
              <% if user_signed_in? %>
                <li class="dropdown auth">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><b><%= current_user.email %></b></a>
                    <div class="dropdown-menu">
                        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item' %> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>               
                        </div>
                </li>
              <% else %>

                 <li  class="active auth"><%= link_to "Sign up", new_user_registration_path, :class => 'nav-link' %></li>
                 <li  class=" active auth"><%= link_to "Login", new_user_session_path, :class => 'nav-link' %></li>
              <% end %>
              <li><%= link_to "Submit your story", new_post_path, :class => 'nav-link' %></li>
            </ul>  
            </div>

        </nav>
     

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-group">
<%= form_for @post do |f| %>

	 <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>post
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control", rows: '4' %>
  </p>
 
  <p>
    <%= f.submit 'Submit', :class => "btn btn-success form-control" %>
  </p>
<% end %>
</div>

app/views/posts/downvote.js.erb
<% if current_user.disliked? @post %>
 $('.downvote-btn-<%= @post.id %>').removeClass('alert-info').addClass('alert-warning')
 $('.upvote-btn-<%= @post.id %>').removeClass('alert-warning')
	<% else %>
 $('.downvote-btn-<%= @post.id %>').removeClass('alert-warning').addClass('alert-info')
	<% end %>
$('.likes-count-<%= @post.id %>').html("<%=@post.weighted_score %>")

app/views/posts/edit.html.erb
<h1>Edit your post</h1>

<div class="form-group">
<%= form_for @post do |f| %>

	 <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>post
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control", rows: '4' %>
  </p>

  <p>
    

   <!--  <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list, value: @post.tag_list.to_s, class: "form-control"%>
 -->


    
      <%= f.label :tag_list %>
      <%= label_tag(:tag_list, "Politics") %>
      <%= f.check_box :tag_list, { :multiple => true }, 'politics', nil %>
      <%= label_tag(:tag_list, "Science") %>
      <%= f.check_box :tag_list, { :multiple => true }, 'science', nil %>
      <%= label_tag(:tag_list, "Social") %>
      <%= f.check_box :tag_list, { :multiple => true }, 'social', nil %>
      <%= label_tag(:tag_list, "Sport") %>
      <%= f.check_box :tag_list, { :multiple => true }, 'sports', nil %>
      <%= label_tag(:tag_list, "Lorem") %>
      <%= f.check_box :tag_list, { :multiple => true }, 'lorem', nil %>
      <%= label_tag(:tag_list, "Ipsum") %>
      <%= f.check_box :tag_list, { :multiple => true }, 'ipsum', nil %>
      




  </p>
 
 <p>
 	<%= f.label :published %><br />
    <%= f.label :published, "Yes", :value => "true"  %>
    <%= f.radio_button :published, true %>
    <%= f.label :published, "No", :value => "false" %>
    <%= f.radio_button :published, false %>

 </p>
  <p>
    <%= f.submit 'Submit', :class => "btn btn-success form-control" %>
  </p>
<% end %>
</div>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% javascript_include_tag("pagination.js") %>
<div class ="wrapper" >

	<div class="tags-container">
		<% @tags.each do |tag| %>
			<%= link_to tag.name, tag_path(tag.name), class: "btn btn-outline-primary" %>
		<% end %>
	</div> 

	<div class="pagination" >
		<%= will_paginate @posts %>
	</div>

	<div class="posts-container">
	  	<% @posts.each do |post| %>
	  		<div class="posts">
			<!-- Body or content of post -->
			<span class="post-id">
			<%= link_to "##{post.id}"  , post_path(post) %>	
			</span>
			<span class="post-date text-muted">
			<%= time_ago_in_words(post.created_at) %> ago
			</span>
			<p calss="post-content">
				<%= simple_format(post.body) %>
			</p> 
			<%= link_to 'Read more', post_path(post)%>

			<div class= "post-tags">
				<% post.tag_list.each do |tag| %>
					<span class="tags"><%= link_to tag, tag_path(tag), class: "btn btn-outline-primary btn-sm" %></span>
				<% end %>
				</div>
			</br>




			<div class="post-actions">
						
						
				<div class= "voting-div">
				<% if current_user.liked? post %>
				  
		     		<%= link_to '', upvote_post_path(post),method: :put, remote: true,
                        class: "fa fa-angle-up alert-warning upvote-btn-#{post.id}", id: post.id%>
				<% else %>
				  
		     		<%= link_to '', upvote_post_path(post),method: :put, remote: true,
                        
                        class: "fa fa-angle-up alert-info upvote-btn-#{post.id}", id: post.id  %>
				<% end %>
				<span class='likes-count-<%= post.id %>' id: post.id ><%= post.weighted_score %></span>


				<% if current_user.disliked? post %>
				  
		     		<%= link_to '', downvote_post_path(post), method: :put, remote: true,
                       
		     		class: "fa fa-angle-down alert-warning downvote-btn-#{post.id}" , id: post.id%>
				<% else %>
		     		<%= link_to '', downvote_post_path(post),method: :put, remote: true,
                        
                        class: "fa fa-angle-down alert-info downvote-btn-#{post.id}", id: post.id %>
				<% end %>
			</div>


				
		     	<%= link_to 'Edit', edit_post_path(post), class: "btn btn-info" %>
		     	

		     	<% if post.published == true %>
		     		<%= link_to 'unpublish', unpublish_posts_path(post), :method => :put, class: "btn btn-danger" %>
		     	<% else %>
		     		<%= link_to 'publish', publish_posts_path(post), :method => :put, class: "btn btn-success" %>
		     	<% end %>

		     	
	     	
	     		
	     	</div>
			
			</br>
			<hr>
			</br>
			</div>
		<% end %>
	 </div>

	 <div class = "pagination" >
		<%= will_paginate @posts %>
	</div>
</div>

app/views/posts/index_published.html.erb
<div class="wrapper">

	<%= form_tag(published_posts_path, method: :get) do %>
	  <%= text_field_tag :search, params[:search] %>
	  <%= submit_tag 'Search', name: nil %>
	<% end %>

	<div class="tags-container">
		<% @tags.each do |tag| %>
			<%= link_to tag.name, tags_published_path(tag.name), class: "btn btn-outline-primary" %>
		<% end %>
	</div>

	<div class="pagination" >
		<%= will_paginate @posts %>
	</div>
	
  	<div class="posts">
	  	<% @posts.each do |post| %>
			<!-- Body or content of post -->
			#<%= post.id %><span class="post-date text-muted"><%= time_ago_in_words(post.created_at) %> ago</span>
			<p>
			<%= simple_format(post.body) %>
			</p>
<!-- 				<%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %> -->						
				<div class= "post-tags">
				<% post.tag_list.each do |tag| %>
					<span class="tags"><%= link_to tag, tag_path(tag), class: "btn btn-outline-primary btn-sm" %></span>
				<% end %>
				</div>

			<hr>
			</br>
			</br>
			</br>

		<% end %>
		</br>
		</br>	
	</div>
	<div class="pagination" >
		<%= will_paginate @posts %>
	</div>	
</div>
  

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-3">
    <!-- 
  	<%= link_to 'Back', :back, :class => "btn btn-primary" %> -->
  </div>
  <div class="col-md-6">
  	<h1>Submit your story</h1>
  	<p>
  	The rules for submitting an articles are simple. 
  	<br>
  		<ul>
  			<li>Try to write grammatically correct</li>
  			<li>Do not use profanity unless its important to the story</li>
  			<li>Post with context, readers must understand what situation you are in and what happened</li>
  		</ul>
  	</p>

	<%= render 'form' %>

	<%= link_to 'Back', :back, :class => "btn btn-primary" %>

  </div>
  <div class="col-md-3"></div>
</div>

app/views/posts/show.html.erb
<p>
  <%= simple_format(@post.body) %>
</p>
<p>
<%= raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
</p>

<%= link_to 'Edit', edit_post_path %> |
<%= link_to 'Back', posts_path %>

app/views/posts/upvote.js.erb
<% if current_user.liked? @post %>
 	$('.upvote-btn-<%= @post.id %>').removeClass('alert-info').addClass('alert-warning')
 	$('.downvote-btn-<%= @post.id %>').removeClass('alert-warning')
<% else %>
 	$('.upvote-btn-<%= @post.id %>').removeClass('alert-warning').addClass('alert-info')
<% end %>
	$('.likes-count-<%= @post.id %>').html("<%=@post.weighted_score %>")

app/views/users/edit_role.html.erb
<h1>Edit your role</h1>

<div class="form-group">
<%= form_for @user do |f| %>

  <p>
    <%= f.label :role %><br>
    <%= f.text_field :role, class: "form-control"%>
   
  </p>
 
  <p>
    <%= f.submit 'Submit', :class => "btn btn-success form-control" %>
  </p>
<% end %>
</div>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class ="wrapper" >


	<div class="pagination" >
		<%= will_paginate @users %>
	</div>

	
	<table class ="table">
		<thead>
		 	<tr>
		 		<th>Role</th>
		 		<th>ID</th>
		 		<th>Email</th>
		 		
		 		<th>Last Sign in</th>
		 		<th>Member Since</th>

		 		<th>Actions</th>
		 	</tr>
	 	</thead>

	 	<tbody>
		  	<% @users.each do |user| %>
		  	<tr>
		  		<th><%= user.role %></th>
		 		<th><%= user.id %></th>
		 		<th><%= user.email %></th>
		 		
		 		<th><%= user.last_sign_in_at %></th>
		 		<th><%= user.created_at %> </th>
		 		<th> <%= link_to 'Edit Role', edit_role_users_path(user), class: "btn btn-warning" %></th>
		 	</tr>
			<% end %>
		</tbody>
	</table>	
	 

	 <div class = "pagination" >
		<%= will_paginate @users %>
	</div>
</div>